# Site settings
title: Wedding Caroline and Avit
email: avit.bhowmik@su.se
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Avit
email: avit.bhowmik@su.se
facebook_username:
twitter_username:
github_username:
address: Sweden
  - line: 
  - line: 
  # Feel free to add more lines here 
telephone: 
copyright: 

# API settings
google_api_key:

# Build settings
markdown: kramdown